import type { CultureRegistryEntry } from "@/types/dashboard";

// Houston keeps a small curated arts/culture registry so the app can always
// attempt mandatory providers first and then grow into future candidate venues.
export const HOUSTON_CULTURE_REGISTRY: CultureRegistryEntry[] = [
  {
    id: "mfah",
    name: "Museum of Fine Arts, Houston",
    displayName: "MFAH",
    city: "Houston",
    area: "Museum District",
    category: "arts",
    priority: "candidate",
    officialUrl: "https://www.mfah.org/",
    eventSourceUrl: "https://www.mfah.org/events",
    providerId: "mfah",
    sourceReliability: "high",
    providerStatus: "audited_limited",
    notes: "Disabled from the active daily refresh after server-side fetches returned HTTP 403. Keep as a blocked re-audit candidate.",
  },
  {
    id: "menil-collection",
    name: "Menil Collection",
    displayName: "Menil",
    city: "Houston",
    area: "Montrose",
    category: "arts",
    priority: "mandatory",
    officialUrl: "https://www.menil.org/",
    eventSourceUrl: "https://www.menil.org/events",
    providerId: "menil",
    sourceReliability: "high",
    providerStatus: "working",
    notes: "Live arts provider using the official Menil events calendar.",
  },
  {
    id: "camh",
    name: "Contemporary Arts Museum Houston",
    displayName: "Contemporary Arts Museum Houston",
    shortName: "CAMH",
    city: "Houston",
    area: "Museum District",
    category: "arts_culture",
    priority: "priority",
    officialUrl: "https://camh.org/",
    eventSourceUrl: "https://camh.org/event-calendar/",
    providerId: "camh",
    sourceReliability: "high",
    providerStatus: "working",
    notes: "Live arts provider using CAMH's official event calendar.",
  },
  {
    id: "meow-wolf-houston",
    name: "Meow Wolf Houston",
    displayName: "Meow Wolf Houston",
    shortName: "Meow Wolf",
    city: "Houston",
    area: "Near Northwest",
    category: "arts_culture",
    priority: "priority",
    officialUrl: "https://meowwolf.com/visit/houston",
    eventSourceUrl: "https://tickets.meowwolf.com/events/houston/",
    providerId: "meow-wolf",
    sourceReliability: "unknown",
    providerStatus: "audited_limited",
    notes: "Priority immersive art and events source. Official Houston page links to an events calendar; server-visible dated event rows were not available in this audit.",
  },
  {
    id: "asia-society-texas",
    name: "Asia Society Texas",
    displayName: "Asia Society Texas",
    shortName: "Asia Society",
    city: "Houston",
    area: "Museum District",
    category: "arts",
    priority: "candidate",
    officialUrl: "https://asiasociety.org/texas",
    eventSourceUrl: "https://asiasociety.org/texas",
    providerId: "asia-society-texas",
    sourceReliability: "unknown",
    providerStatus: "audited_limited",
    notes: "Disabled from the active daily refresh after server-side fetches returned HTTP 403. Keep as a blocked re-audit candidate.",
  },
  {
    id: "blaffer-art-museum",
    name: "Blaffer Art Museum",
    displayName: "Blaffer Art Museum",
    shortName: "Blaffer",
    city: "Houston",
    area: "University of Houston",
    category: "arts",
    priority: "priority",
    officialUrl: "https://blafferartmuseum.org/",
    eventSourceUrl: "https://blafferartmuseum.org/events/",
    providerId: "blaffer",
    sourceReliability: "high",
    providerStatus: "working",
    notes: "Live arts provider using Blaffer Art Museum's official events archive.",
  },
  {
    id: "buffalo-bayou-partnership",
    name: "Buffalo Bayou Partnership",
    displayName: "Buffalo Bayou Partnership",
    shortName: "Buffalo Bayou",
    city: "Houston",
    area: "Buffalo Bayou",
    category: "arts_culture",
    priority: "priority",
    officialUrl: "https://buffalobayou.org/",
    eventSourceUrl: "https://buffalobayou.org/calendar/",
    providerId: "buffalo-bayou",
    sourceReliability: "high",
    providerStatus: "working",
    notes: "Live community-events source using Buffalo Bayou's official homepage cards and calendar pages.",
  },
  {
    id: "discovery-green",
    name: "Discovery Green",
    displayName: "Discovery Green",
    city: "Houston",
    area: "Downtown",
    category: "arts",
    priority: "priority",
    officialUrl: "https://www.discoverygreen.com/",
    eventSourceUrl: "https://www.discoverygreen.com/events/",
    providerId: "discovery-green",
    sourceReliability: "high",
    providerStatus: "working",
    notes: "Live arts and community-events provider using Discovery Green's official event pages.",
  },
  {
    id: "project-row-houses",
    name: "Project Row Houses",
    displayName: "Project Row Houses",
    shortName: "PRH",
    city: "Houston",
    area: "Third Ward",
    category: "arts_culture",
    priority: "priority",
    officialUrl: "https://projectrowhouses.org/",
    eventSourceUrl: "https://projectrowhouses.org/",
    providerId: "project-row-houses",
    sourceReliability: "limited",
    providerStatus: "audited_limited",
    notes: "First-party homepage text is useful, but the official Eventbrite calendar is not used for parsing in this step.",
  },
  {
    id: "lawndale-art-center",
    name: "Lawndale Art Center",
    displayName: "Lawndale Art Center",
    shortName: "Lawndale",
    city: "Houston",
    area: "Museum District",
    category: "arts",
    priority: "priority",
    officialUrl: "https://lawndaleartcenter.org/",
    eventSourceUrl: "https://lawndaleartcenter.org/events/",
    providerId: "lawndale",
    sourceReliability: "high",
    providerStatus: "working",
    notes: "Live arts provider using Lawndale's official events page, with homepage fallback if needed.",
  },
  {
    id: "orange-show",
    name: "Orange Show Center for Visionary Art",
    displayName: "Orange Show",
    shortName: "Orange Show",
    city: "Houston",
    area: "East End",
    category: "arts_culture",
    priority: "priority",
    officialUrl: "https://orangeshow.org/",
    eventSourceUrl: "https://www.orangeshow.org/calendar",
    providerId: "orange-show",
    sourceReliability: "medium",
    providerStatus: "working",
    notes: "Live arts provider using the official Orange Show calendar, with Orange Show, Beer Can House, Smither Park, and Art Car programming.",
  },
];

export const HOUSTON_MANDATORY_CULTURE_SOURCES = HOUSTON_CULTURE_REGISTRY.filter(
  (entry) => entry.priority === "mandatory",
);
