import type { SportsRegistryEntry } from "@/types/dashboard";

export const HOUSTON_SPORTS_REGISTRY: SportsRegistryEntry[] = [
  {
    id: "houston-astros",
    displayName: "Houston Astros",
    league: "MLB",
    sport: "Baseball",
    homeVenue: "Daikin Park",
    city: "Houston",
    priority: "mandatory",
    officialUrl: "https://www.mlb.com/astros",
    scheduleUrl: "https://www.mlb.com/astros/schedule",
    providerId: "astros",
    providerStatus: "working",
    notes: "Live provider audits the public MLB schedule endpoint; keep the official schedule page as the source anchor.",
  },
  {
    id: "houston-rockets",
    displayName: "Houston Rockets",
    league: "NBA",
    sport: "Basketball",
    homeVenue: "Toyota Center",
    city: "Houston",
    priority: "mandatory",
    officialUrl: "https://www.nba.com/rockets",
    scheduleUrl: "https://www.nba.com/rockets/schedule",
    providerId: null,
    providerStatus: "audited_limited",
    notes: "Official schedule page reachable; server HTML does not expose clean schedule rows, and the NBA client-side app internals are intentionally not parsed.",
  },
  {
    id: "houston-texans",
    displayName: "Houston Texans",
    league: "NFL",
    sport: "Football",
    homeVenue: "NRG Stadium",
    city: "Houston",
    priority: "mandatory",
    officialUrl: "https://www.houstontexans.com/",
    scheduleUrl: "https://www.houstontexans.com/schedule/",
    providerId: null,
    providerStatus: "audited_limited",
    notes: "Official schedule page reachable; 2026 page found; server HTML does not expose clean schedule rows, and the print schedule asset is intentionally not parsed.",
  },
  {
    id: "houston-dynamo-fc",
    displayName: "Houston Dynamo FC",
    league: "MLS",
    sport: "Soccer",
    homeVenue: "Shell Energy Stadium",
    city: "Houston",
    priority: "mandatory",
    officialUrl: "https://www.houstondynamofc.com/",
    scheduleUrl: "https://www.houstondynamofc.com/schedule/download",
    providerId: "dynamo",
    providerStatus: "working",
    notes: "Live provider uses the official downloadable calendar feed from the schedule download page.",
  },
  {
    id: "houston-dash",
    displayName: "Houston Dash",
    league: "NWSL",
    sport: "Soccer",
    homeVenue: "Shell Energy Stadium",
    city: "Houston",
    priority: "mandatory",
    officialUrl: "https://www.houstondynamofc.com/houstondash/",
    scheduleUrl: "https://www.houstondynamofc.com/houstondash/schedule/",
    providerId: "dash",
    providerStatus: "limited",
    notes: "Official schedule page is parseable; live coverage depends on the current date window.",
  },
  {
    id: "houston-sabercats",
    displayName: "Houston SaberCats",
    league: "MLR",
    sport: "Rugby",
    homeVenue: "SaberCats Stadium",
    city: "Houston",
    priority: "inactive",
    officialUrl: "https://www.houstonsabercats.com/",
    scheduleUrl: null,
    providerId: null,
    providerStatus: "inactive",
    notes: "Not competing in MLR in 2026; keep as a historical/tracked Houston pro sports entry.",
  },
];

export const HOUSTON_MANDATORY_SPORTS = HOUSTON_SPORTS_REGISTRY.filter(
  (entry) => entry.priority === "mandatory",
);
